prompt: A pineapple
negative_prompt: cropped, out of frame, morbid, mutilated, bizarre, corrupted, malformed, low quality, artifacts, watermark, signature
guide: IFGuide
iterations: 50000
lr: 1e-4
eps: 1e-4
weight_decay: 0.1
guidance_scale: 100
t_range: [0.02, 0.98]
theta_range: [0, 360]
phi_range: [0, 100]
focal_range: [0.7, 1.35]
radius_range: [1, 1.5]
sample_range: [0.25, 3]
train_render_dims: [64, 64]
train_render_samples: 64
check_render_dims: [128, 128]
check_render_samples: 64
check_frame_rate: 12
output_path: output/pineapple
output_interval: 250
device: cuda
dtype: float16
